[package]
name = "taskr"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
rusqlite = { version = "0.36.0", features = ["chrono", "uuid"] }
uuid = { version = "1.17.0", features = ["v4",] }
